import { type Dictionary, insert, t } from 'intlayer';

const appContent = {
  key: 'app',
  content: {
    install: t({
      en: 'Install',
      nl: 'Installeer',
      fr: 'Installer',
      de: 'Installieren',
      es: 'Instalar',
      it: 'Installa',
      ar: 'تثبيت',
      cs: 'Instalovat',
      et: 'Paigalda',
      eu: 'Instalatu',
      gl: 'Instalar',
      hu: 'Telepítés',
      id: 'Pasang',
      ja: 'インストール',
      lt: 'Įdiegti',
      pl: 'Zainstaluj',
      pt: 'Instalar',
      ru: 'Установить',
      sq: 'Instalo',
      sr: 'Instaliraj',
      tr: 'Yükle',
      'zh-Hans': '安装',
      'zh-Hant': '安裝',
    }),
    loading: t({
      en: 'Loading list of available modules',
      nl: 'Lijst met beschikbare modules aan het laden',
      fr: 'Chargement de la liste des modules disponibles',
      de: 'Liste verfügbarer Module wird geladen',
      es: 'Cargando la lista de módulos disponibles',
      it: 'Caricamento elenco dei moduli disponibili',
      ar: 'جارٍ تحميل قائمة الوحدات المتاحة',
      cs: 'Načítání seznamu dostupných modulů',
      et: 'Saadaval moodulite nimekirja laadimine',
      eu: 'Modulu erabilgarrien zerrenda kargatzen',
      gl: 'Cargando a lista de módulos dispoñibles',
      hu: 'Elérhető modulok listájának betöltése',
      id: 'Memuat daftar modul yang tersedia',
      ja: '利用可能なモジュールのリストを読み込み中',
      lt: 'Įkeliamas galimų modulių sąrašas',
      pl: 'Ładowanie listy dostępnych modułów',
      pt: 'Carregando lista de módulos disponíveis',
      ru: 'Загрузка списка доступных модулей',
      sq: 'Duke ngarkuar listën e moduleve të disponueshme',
      sr: 'Učitavanje liste dostupnih modula',
      tr: 'Mevcut modüllerin listesi yükleniyor',
      'zh-Hans': '正在加载可用模块列表',
      'zh-Hant': '正在載入可用模組清單',
    }),
    select_channel: t({
      en: 'Select channel',
      nl: 'Selecteer kanaal',
      fr: 'Sélectionner un canal',
      de: 'Kanal auswählen',
      es: 'Seleccionar canal',
      it: 'Seleziona canale',
      ar: 'اختر قناة',
      cs: 'Vyberte kanál',
      et: 'Vali kanal',
      eu: 'Hautatu kanala',
      gl: 'Seleccione o canal',
      hu: 'Csatorna kiválasztása',
      id: 'Pilih saluran',
      ja: 'チャンネルを選択',
      lt: 'Pasirinkite kanalą',
      pl: 'Wybierz kanał',
      pt: 'Selecionar canal',
      ru: 'Выберите канал',
      sq: 'Zgjidhni kanalin',
      sr: 'Izaberite kanal',
      tr: 'Kanalı seçin',
      'zh-Hans': '选择频道',
      'zh-Hant': '選擇頻道',
    }),
    checkmark: t({
      en: 'Checkmark',
      nl: 'Vinkje',
      fr: 'Coche',
      de: 'Häkchen',
      es: 'Marca de verificación',
      it: 'Segno di spunta',
      ar: 'علامة اختيار',
      cs: 'Zaškrtnutí',
      et: 'Märge',
      eu: 'Marka',
      gl: 'Marca de verificación',
      hu: 'Pipa',
      id: 'Tanda centang',
      ja: 'チェックマーク',
      lt: 'Žymeklis',
      pl: 'Zaznaczenie',
      pt: 'Marca de seleção',
      ru: 'Галочка',
      sq: 'Shenjë kontrolli',
      sr: 'Potvrda',
      tr: 'Onay işareti',
      'zh-Hans': '对号',
      'zh-Hant': '勾選標記',
    }),
    update: t({
      en: 'Update',
      nl: 'Bijwerken',
      fr: 'Mettre à jour',
      de: 'Aktualisieren',
      es: 'Actualizar',
      it: 'Aggiorna',
      ar: 'تحديث',
      cs: 'Aktualizovat',
      et: 'Uuenda',
      eu: 'Eguneratu',
      gl: 'Actualizar',
      hu: 'Frissítés',
      id: 'Perbarui',
      ja: 'アップデート',
      lt: 'Atnaujinti',
      pl: 'Aktualizuj',
      pt: 'Atualizar',
      ru: 'Обновить',
      sq: 'Përditëso',
      sr: 'Ažuriraj',
      tr: 'Güncelle',
      'zh-Hans': '更新',
      'zh-Hant': '更新',
    }),
    uninstall: t({
      en: 'Uninstall',
      nl: 'Verwijderen',
      fr: 'Désinstaller',
      de: 'Deinstallieren',
      es: 'Desinstalar',
      it: 'Disinstalla',
      ar: 'إلغاء التثبيت',
      cs: 'Odinstalovat',
      et: 'Eemalda',
      eu: 'Desinstalatu',
      gl: 'Desinstalar',
      hu: 'Eltávolítás',
      id: 'Hapus pemasangan',
      ja: 'アンインストール',
      lt: 'Pašalinti',
      pl: 'Odinstaluj',
      pt: 'Desinstalar',
      ru: 'Удалить',
      sq: 'Çinstalo',
      sr: 'Deinstaliraj',
      tr: 'Kaldır',
      'zh-Hans': '卸载',
      'zh-Hant': '解除安裝',
    }),
    pre_release: t({
      en: 'Pre release',
      nl: 'Pre-release',
      fr: 'Pré-version',
      de: 'Vorabversion',
      es: 'Prelanzamiento',
      it: 'Pre-rilascio',
      ar: 'إصدار تجريبي',
      cs: 'Předběžné vydání',
      et: 'Eelväljaanne',
      eu: 'Aurre-bertsioa',
      gl: 'Pre-lanzamento',
      hu: 'Előzetes kiadás',
      id: 'Pra-rilis',
      ja: 'プレリリース',
      lt: 'Priešleidimas',
      pl: 'Wersja przedpremierowa',
      pt: 'Pré-lançamento',
      ru: 'Предрелиз',
      sq: 'Parapublikim',
      sr: 'Prethodno izdanje',
      tr: 'Ön sürüm',
      'zh-Hans': '预发布',
      'zh-Hant': '預發布',
    }),
    installed: t({
      en: 'Installed',
      nl: 'Geïnstalleerd',
      fr: 'Installé',
      de: 'Installiert',
      es: 'Instalado',
      it: 'Installato',
      ar: 'مثبت',
      cs: 'Nainstalováno',
      et: 'Paigaldatud',
      eu: 'Instalatuta',
      gl: 'Instalado',
      hu: 'Telepítve',
      id: 'Terpasang',
      ja: 'インストール済み',
      lt: 'Įdiegta',
      pl: 'Zainstalowano',
      pt: 'Instalado',
      ru: 'Установлено',
      sq: 'Instaluar',
      sr: 'Instalirano',
      tr: 'Yüklendi',
      'zh-Hans': '已安装',
      'zh-Hant': '已安裝',
    }),
    uninstall_this_module: t({
      en: 'Uninstall this module',
      nl: 'Verwijder deze module',
      fr: 'Désinstaller ce module',
      de: 'Dieses Modul deinstallieren',
      es: 'Desinstalar este módulo',
      it: 'Disinstalla questo modulo',
      ar: 'إلغاء تثبيت هذه الوحدة',
      cs: 'Odinstalovat tento modul',
      et: 'Eemalda see moodul',
      eu: 'Desinstalatu modulua',
      gl: 'Desinstalar este módulo',
      hu: 'Távolítsa el ezt a modult',
      id: 'Hapus modul ini',
      ja: 'このモジュールをアンインストール',
      lt: 'Pašalinti šį modulį',
      pl: 'Odinstaluj ten moduł',
      pt: 'Desinstalar este módulo',
      ru: 'Удалить этот модуль',
      sq: 'Çinstalo këtë modul',
      sr: 'Deinstaliraj ovaj modul',
      tr: 'Bu modülü kaldır',
      'zh-Hans': '卸载此模块',
      'zh-Hant': '解除安裝此模組',
    }),
    latest_version_installed: t({
      en: 'Latest version is installed',
      nl: 'Nieuwste versie is geïnstalleerd',
      fr: 'La dernière version est installée',
      de: 'Neueste Version ist installiert',
      es: 'La última versión está instalada',
      it: 'L’ultima versione è installata',
      ar: 'أحدث إصدار مثبت',
      cs: 'Nejnovější verze je nainstalována',
      et: 'Viimane versioon on paigaldatud',
      eu: 'Azken bertsioa instalatuta dago',
      gl: 'A última versión está instalada',
      hu: 'A legújabb verzió telepítve van',
      id: 'Versi terbaru telah terpasang',
      ja: '最新バージョンがインストールされています',
      lt: 'Naujausia versija įdiegta',
      pl: 'Najnowsza wersja jest zainstalowana',
      pt: 'A versão mais recente está instalada',
      ru: 'Установлена последняя версия',
      sq: 'Versioni më i fundit është instaluar',
      sr: 'Najnovija verzija je instalirana',
      tr: 'En son sürüm yüklendi',
      'zh-Hans': '已安装最新版本',
      'zh-Hant': '已安裝最新版本',
    }),
    go_to_home_page_of_module: t({
      en: 'Go to home page of module',
      nl: 'Ga naar de homepage van de module',
      fr: 'Aller à la page d’accueil du module',
      de: 'Zur Startseite des Moduls gehen',
      es: 'Ir a la página principal del módulo',
      it: 'Vai alla home page del modulo',
      ar: 'اذهب إلى الصفحة الرئيسية للوحدة',
      cs: 'Přejít na domovskou stránku modulu',
      et: 'Mine mooduli avalehele',
      eu: 'Joan moduluko orri nagusira',
      gl: 'Ir á páxina de inicio do módulo',
      hu: 'Ugrás a modul kezdőlapjára',
      id: 'Buka halaman utama modul',
      ja: 'モジュールのホームページへ',
      lt: 'Eiti į modulio pagrindinį puslapį',
      pl: 'Przejdź do strony głównej modułu',
      pt: 'Ir para a página inicial do módulo',
      ru: 'Перейти на главную страницу модуля',
      sq: 'Shko te faqja kryesore e modulit',
      sr: 'Idi na početnu stranicu modula',
      tr: 'Modülün ana sayfasına git',
      'zh-Hans': '前往模块主页',
      'zh-Hant': '前往模組主頁',
    }),
    channel: t({
      en: 'Channel',
      nl: 'Kanaal',
      fr: 'Canal',
      de: 'Kanal',
      es: 'Canal',
      it: 'Canale',
      ar: 'قناة',
      cs: 'Kanál',
      et: 'Kanal',
      eu: 'Kanala',
      gl: 'Canle',
      hu: 'Csatorna',
      id: 'Saluran',
      ja: 'チャンネル',
      lt: 'Kanalas',
      pl: 'Kanał',
      pt: 'Canal',
      ru: 'Канал',
      sq: 'Kanal',
      sr: 'Kanal',
      tr: 'Kanal',
      'zh-Hans': '频道',
      'zh-Hant': '頻道',
    }),
    show_prereleases: t({
      en: 'Show pre-releases',
      nl: 'Toon pre-releases',
      fr: 'Afficher les pré-versions',
      de: 'Vorabversionen anzeigen',
      es: 'Mostrar pre-lanzamientos',
      it: 'Mostra pre-release',
      ar: 'إظهار الإصدارات التجريبية',
      cs: 'Zobrazit předběžná vydání',
      et: 'Kuva eeltõmmised',
      eu: 'Erakutsi aurre-bertsioak',
      gl: 'Mostrar pre-lanzamentos',
      hu: 'Előzetes kiadások megjelenítése',
      id: 'Tampilkan pra-rilis',
      ja: 'プレリリースを表示',
      lt: 'Rodyti priešleidimus',
      pl: 'Pokaż wersje przedpremierowe',
      pt: 'Mostrar pré-lançamentos',
      ru: 'Показать предрелизы',
      sq: 'Shfaq parapublikimet',
      sr: 'Prikaži prethodna izdanja',
      tr: 'Ön sürümleri göster',
      'zh-Hans': '显示预发布版本',
      'zh-Hant': '顯示預發布版本',
    }),
    allow_prereleases_checkbox_description: t({
      en: 'When checked shows pre-releases. Pre-releases are releases that a module developer has not yet marked as stable.',
      nl: 'Indien aangevinkt worden pre-releases getoond. Pre-releases zijn versies die een moduleontwikkelaar nog niet als stabiel heeft gemarkeerd.',
      fr: 'Si coché, affiche les pré-versions. Les pré-versions sont des versions qu’un développeur de module n’a pas encore marquées comme stables.',
      de: 'Wenn aktiviert, werden Vorabversionen angezeigt. Vorabversionen sind Versionen, die ein Modul-Entwickler noch nicht als stabil markiert hat.',
      es: 'Si está marcado, muestra pre-lanzamientos. Los pre-lanzamientos son versiones que el desarrollador del módulo aún no ha marcado como estables.',
      it: 'Se selezionato mostra le pre-release. Le pre-release sono versioni che lo sviluppatore del modulo non ha ancora contrassegnato come stabili.',
      ar: 'عند التحديد تظهر الإصدارات التجريبية. الإصدارات التجريبية هي إصدارات لم يتم اعتبارها مستقرة بعد من قبل مطور الوحدة.',
      cs: 'Pokud je zaškrtnuto, zobrazí se předběžná vydání. Předběžná vydání jsou verze, které vývojář modulu ještě neoznačil jako stabilní.',
      et: 'Kui märgitud, kuvatakse eeltõmmised. Eeltõmmised on versioonid, mida mooduli arendaja pole veel stabiilseks märkinud.',
      eu: 'Hautatuta, aurre-bertsioak erakusten dira. Aurre-bertsioak modulu-garatzaileak oraindik egonkortzat jo ez dituen bertsioak dira.',
      gl: 'Se está marcado, móstranse pre-lanzamentos. Os pre-lanzamentos son versións que o desenvolvedor do módulo aínda non marcou como estables.',
      hu: 'Ha be van jelölve, előzetes kiadások jelennek meg. Az előzetes kiadások olyan verziók, amelyeket a modul fejlesztője még nem jelölt stabilnak.',
      id: 'Jika dicentang, menampilkan pra-rilis. Pra-rilis adalah rilis yang belum dianggap stabil oleh pengembang modul.',
      ja: 'チェックするとプレリリースが表示されます。プレリリースは、モジュール開発者がまだ安定版とみなしていないリリースです。',
      lt: 'Pažymėjus rodomi priešleidimai. Priešleidimai yra leidimai, kurių modulio kūrėjas dar nepažymėjo kaip stabilių.',
      pl: 'Po zaznaczeniu pokazuje wersje przedpremierowe. Wersje przedpremierowe to wersje, które deweloper modułu nie oznaczył jeszcze jako stabilne.',
      pt: 'Quando marcado, mostra pré-lançamentos. Pré-lançamentos são versões que o desenvolvedor do módulo ainda não marcou como estáveis.',
      ru: 'Если отмечено, показываются предрелизы. Предрелизы — это версии, которые разработчик модуля ещё не отметил как стабильные.',
      sq: 'Kur është i zgjedhur, shfaq parapublikimet. Parapublikimet janë versione që zhvilluesi i modulit nuk i ka shënuar ende si të qëndrueshme.',
      sr: 'Kada je označeno, prikazuje prethodna izdanja. Prethodna izdanja su izdanja koja programer modula još nije označio kao stabilna.',
      tr: 'Seçildiğinde ön sürümler gösterilir. Ön sürümler, modül geliştiricisinin henüz kararlı olarak işaretlemediği sürümlerdir.',
      'zh-Hans':
        '选中时显示预发布版本。预发布版本是模块开发者尚未标记为稳定的版本。',
      'zh-Hant':
        '勾選時顯示預發布版本。預發布版本是模組開發者尚未標記為穩定的版本。',
    }),
    search_for_a_module: t({
      en: 'Search for a module',
      nl: 'Zoek een module',
      fr: 'Rechercher un module',
      de: 'Nach einem Modul suchen',
      es: 'Buscar un módulo',
      it: 'Cerca un modulo',
      ar: 'ابحث عن وحدة',
      cs: 'Hledat modul',
      et: 'Otsi moodulit',
      eu: 'Bilatu modulua',
      gl: 'Buscar un módulo',
      hu: 'Modul keresése',
      id: 'Cari modul',
      ja: 'モジュールを検索',
      lt: 'Ieškoti modulio',
      pl: 'Szukaj modułu',
      pt: 'Pesquisar um módulo',
      ru: 'Поиск модуля',
      sq: 'Kërko për një modul',
      sr: 'Pretraži modul',
      tr: 'Modül ara',
      'zh-Hans': '搜索模块',
      'zh-Hant': '搜尋模組',
    }),
    no_modules_found: t({
      en: 'No modules found',
      nl: 'Geen modules gevonden',
      fr: 'Aucun module trouvé',
      de: 'Keine Module gefunden',
      es: 'No se encontraron módulos',
      it: 'Nessun modulo trovato',
      ar: 'لم يتم العثور على وحدات',
      cs: 'Nebyly nalezeny žádné moduly',
      et: 'Mooduleid ei leitud',
      eu: 'Ez da modulurik aurkitu',
      gl: 'Non se atoparon módulos',
      hu: 'Nem található modul',
      id: 'Tidak ada modul ditemukan',
      ja: 'モジュールが見つかりません',
      lt: 'Modulių nerasta',
      pl: 'Nie znaleziono modułów',
      pt: 'Nenhum módulo encontrado',
      ru: 'Модули не найдены',
      sq: 'Nuk u gjet asnjë modul',
      sr: 'Nema pronađenih modula',
      tr: 'Modül bulunamadı',
      'zh-Hans': '未找到模块',
      'zh-Hant': '找不到模組',
    }),
    release_stats_installed: t({
      en: insert(
        'Installed {{installedVersion}}, latest {{latestVersion}} on {{publishedAt}} with {{downloads}} downloads',
      ),
      nl: insert(
        'Geïnstalleerd {{installedVersion}}, laatste {{latestVersion}} op {{publishedAt}} met {{downloads}} downloads',
      ),
      fr: insert(
        'Installé {{installedVersion}}, dernière {{latestVersion}} le {{publishedAt}} avec {{downloads}} téléchargements',
      ),
      de: insert(
        'Installiert {{installedVersion}}, neueste {{latestVersion}} am {{publishedAt}} mit {{downloads}} Downloads',
      ),
      es: insert(
        'Instalado {{installedVersion}}, última {{latestVersion}} el {{publishedAt}} con {{downloads}} descargas',
      ),
      it: insert(
        'Installato {{installedVersion}}, ultima {{latestVersion}} il {{publishedAt}} con {{downloads}} download',
      ),
      ar: insert(
        'تم التثبيت {{installedVersion}}، الأحدث {{latestVersion}} في {{publishedAt}} مع {{downloads}} تنزيلات',
      ),
      cs: insert(
        'Nainstalováno {{installedVersion}}, nejnovější {{latestVersion}} dne {{publishedAt}} s {{downloads}} staženími',
      ),
      et: insert(
        'Paigaldatud {{installedVersion}}, viimane {{latestVersion}} kuupäeval {{publishedAt}} koos {{downloads}} allalaadimisega',
      ),
      eu: insert(
        'Instalatuta {{installedVersion}}, azkena {{latestVersion}} {{publishedAt}}an {{downloads}} deskarga',
      ),
      gl: insert(
        'Instalado {{installedVersion}}, última {{latestVersion}} o {{publishedAt}} con {{downloads}} descargas',
      ),
      hu: insert(
        'Telepítve: {{installedVersion}}, legújabb: {{latestVersion}} ekkor: {{publishedAt}}, letöltések száma: {{downloads}}',
      ),
      id: insert(
        'Terpasang {{installedVersion}}, terbaru {{latestVersion}} pada {{publishedAt}} dengan {{downloads}} unduhan',
      ),
      ja: insert(
        'インストール済み {{installedVersion}}、最新 {{latestVersion}}（{{publishedAt}}、{{downloads}} ダウンロード）',
      ),
      lt: insert(
        'Įdiegta {{installedVersion}}, naujausia {{latestVersion}} {{publishedAt}} su {{downloads}} atsisiuntimų',
      ),
      pl: insert(
        'Zainstalowano {{installedVersion}}, najnowsza {{latestVersion}} w dniu {{publishedAt}} z {{downloads}} pobrań',
      ),
      pt: insert(
        'Instalado {{installedVersion}}, última {{latestVersion}} em {{publishedAt}} com {{downloads}} downloads',
      ),
      ru: insert(
        'Установлено {{installedVersion}}, последняя {{latestVersion}} от {{publishedAt}}, {{downloads}} загрузок',
      ),
      sq: insert(
        'Instaluar {{installedVersion}}, më e fundit {{latestVersion}} më {{publishedAt}} me {{downloads}} shkarkime',
      ),
      sr: insert(
        'Instalirano {{installedVersion}}, najnovije {{latestVersion}} dana {{publishedAt}} sa {{downloads}} preuzimanja',
      ),
      tr: insert(
        'Yüklendi {{installedVersion}}, en son {{latestVersion}} {{publishedAt}} tarihinde {{downloads}} indirme ile',
      ),
      'zh-Hans': insert(
        '已安装 {{installedVersion}}，最新 {{latestVersion}} 于 {{publishedAt}}，下载量 {{downloads}}',
      ),
      'zh-Hant': insert(
        '已安裝 {{installedVersion}}，最新 {{latestVersion}} 於 {{publishedAt}}，下載次數 {{downloads}}',
      ),
    }),
    release_stats_notinstalled: t({
      en: insert(
        'Latest {{latestVersion}} on {{publishedAt}} with {{downloads}} downloads',
      ),
      nl: insert(
        'Laatste {{latestVersion}} op {{publishedAt}} met {{downloads}} downloads',
      ),
      fr: insert(
        'Dernière {{latestVersion}} le {{publishedAt}} avec {{downloads}} téléchargements',
      ),
      de: insert(
        'Neueste {{latestVersion}} am {{publishedAt}} mit {{downloads}} Downloads',
      ),
      es: insert(
        'Última {{latestVersion}} el {{publishedAt}} con {{downloads}} descargas',
      ),
      it: insert(
        'Ultima {{latestVersion}} il {{publishedAt}} con {{downloads}} download',
      ),
      ar: insert(
        'الأحدث {{latestVersion}} في {{publishedAt}} مع {{downloads}} تنزيلات',
      ),
      cs: insert(
        'Nejnovější {{latestVersion}} dne {{publishedAt}} s {{downloads}} staženími',
      ),
      et: insert(
        'Viimane {{latestVersion}} kuupäeval {{publishedAt}} koos {{downloads}} allalaadimisega',
      ),
      eu: insert(
        'Azkena {{latestVersion}} {{publishedAt}}an {{downloads}} deskarga',
      ),
      gl: insert(
        'Última {{latestVersion}} o {{publishedAt}} con {{downloads}} descargas',
      ),
      hu: insert(
        'Legújabb: {{latestVersion}} ekkor: {{publishedAt}}, letöltések száma: {{downloads}}',
      ),
      id: insert(
        'Terbaru {{latestVersion}} pada {{publishedAt}} dengan {{downloads}} unduhan',
      ),
      ja: insert(
        '最新 {{latestVersion}}（{{publishedAt}}、{{downloads}} ダウンロード）',
      ),
      lt: insert(
        'Naujausia {{latestVersion}} {{publishedAt}} su {{downloads}} atsisiuntimų',
      ),
      pl: insert(
        'Najnowsza {{latestVersion}} w dniu {{publishedAt}} z {{downloads}} pobrań',
      ),
      pt: insert(
        'Última {{latestVersion}} em {{publishedAt}} com {{downloads}} downloads',
      ),
      ru: insert(
        'Последняя {{latestVersion}} от {{publishedAt}}, {{downloads}} загрузок',
      ),
      sq: insert(
        'Më e fundit {{latestVersion}} më {{publishedAt}} me {{downloads}} shkarkime',
      ),
      sr: insert(
        'Najnovije {{latestVersion}} dana {{publishedAt}} sa {{downloads}} preuzimanja',
      ),
      tr: insert(
        'En son {{latestVersion}} {{publishedAt}} tarihinde {{downloads}} indirme ile',
      ),
      'zh-Hans': insert(
        '最新 {{latestVersion}} 于 {{publishedAt}}，下载量 {{downloads}}',
      ),
      'zh-Hant': insert(
        '最新 {{latestVersion}} 於 {{publishedAt}}，下載次數 {{downloads}}',
      ),
    }),
    by_maintainer: t({
      en: insert('by {{maintainer}}'),
      nl: insert('door {{maintainer}}'),
      fr: insert('par {{maintainer}}'),
      de: insert('von {{maintainer}}'),
      es: insert('por {{maintainer}}'),
      it: insert('da {{maintainer}}'),
      ar: insert('{{maintainer}} بواسطة'),
      cs: insert('{{maintainer}} od'),
      et: insert('{{maintainer}} poolt'),
      eu: insert('{{maintainer}} arabera'),
      gl: insert('por {{maintainer}}'),
      hu: insert('{{maintainer}} által'),
      id: insert('{{maintainer}} oleh'),
      ja: insert('{{maintainer}} 作成者'),
      lt: insert('{{maintainer}} pagal'),
      pl: insert('przez {{maintainer}}'),
      pt: insert('por {{maintainer}}'),
      ru: insert('от {{maintainer}}'),
      sq: insert('{{maintainer}} nga'),
      sr: insert('{{maintainer}} od'),
      tr: insert('{{maintainer}} tarafından'),
      'zh-Hans': insert('{{maintainer}} 由'),
      'zh-Hant': insert('{{maintainer}} 由'),
    }),
  },
} satisfies Dictionary;

export default appContent;
